<footer class="col-lg-12">
            <hr/>
           Magnesio y Mosquetón es una aplicación web desarrollada por Alejandro Seva para el proyecto final del Ciclo Superior de Desarrollo de Aplicaciones Web - Las imágenes han sido recogidas de <a href="www.pixabay.com">www.pixabay.com</a> y solo son orientativas, no reflejan el trazado real de las vías de escalada - Cualquier duda, sugerencia o consulta: <a href="mailto:asevaa@fp.uoc.edu?subject=Questions">Pulse aquí</a> - <?php echo  date("Y"); ?>
        </footer>
</body>
</html>